//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProduct("Cake.SqlServer")]
[assembly: AssemblyVersion("2.0.2.0")]
[assembly: AssemblyFileVersion("2.0.2.0")]
[assembly: AssemblyInformationalVersion("2.0.2+4.Branch.master.Sha.d36ff31fd7a3ffabf77a62b3adf953f48cacf3f5")]
[assembly: AssemblyCopyright("Copyright (c) 2016 - 2016 AMV Software")]

[assembly: InternalsVisibleTo("Tests")]
