//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProduct("Cake.SqlServer")]
[assembly: AssemblyVersion("1.5.1.0")]
[assembly: AssemblyFileVersion("1.5.1.0")]
[assembly: AssemblyInformationalVersion("1.5.1-backpac.1+13.Branch.backpac.Sha.ea1d7b9246a302adb0f73eb9f55a8375480a503c")]
[assembly: AssemblyCopyright("Copyright (c) 2016 - 2016 AMV Software")]

[assembly: InternalsVisibleTo("Tests")]